### ISSUE TITLE
Testing term-send-input with IPython 5

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [ffevotte/isend-mode.el#8] opened 2016-07-17 16:57 UTC
As I reported in this other issue https://github.com/ffevotte/isend-mode.el/issues/6 I am having problems getting isend to work with the latest IPython 5 terminal. I thought this would be a good opportunity for me to try contribute to this great package, since it has been a life saver since I started using it!

I have a relatively basic knowledge of Elisp, but I was able to follow most of the logic in `isend-mode.el`. I suspect part of the problem that I am having is coming from what's being sent to the terminal, since the IPython 5 interpreter works perfectly fine otherwise running within my ansi-term buffers. 

The key seems to be these lines: https://github.com/ffevotte/isend-mode.el/blob/master/isend-mode.el#L278-L282 which read:

      (cond
        ;; Terminal buffer: specifically call `term-send-input'
        ;; to handle both the char and line modes of `ansi-term'.
        ((eq major-mode 'term-mode)
         (term-send-input))

What does `(eq major-mode 'term-mode)` do? Is it a comparison to make sure that it's a `term-mode` before we invoke `term-send-input` ?  

How does `term-send-input` know what to send to what buffer? I know that it's wrapped up within two statements:

*   ` (with-temp-buffer` ...
*    `(with-current-buffer destination` ... where destination holds the buffer we associate beforehand.

Also, how can I test interactively sending a simple string to a given buffer (called "ipy" in my case) where I have an IPython terminal running?

**Comment by ffevotte** [comment] 2016-07-17 18:50
`ansi-term` has two modes: char mode and line mode. When in char mode, everything typed in the emacs buffer is sent right away to the underlying process. When in line-mode, the emacs buffer acts as a buffer (in the non-emacs sense of the term) and only sends characters to the underlying process every once in a while, by batches. This is what `term-send-input` does: it sends to the process all characters which have been buffered in emacs.

The `(eq major-mode 'term-mode)` test checks whether the target buffer is in `term-mode`.
- If so, it uses `term-send-input` to make sure that the underlying process is aware of everything typed so far, whatever the mode the terminal is in.
- If the target buffer is not a terminal, then it does whatever <kbd>RET</kbd> is bound to.

**Comment by ffevotte** [comment] 2016-07-17 18:58
I'm not sure I understand your last question. If you mean to test sending a string with the minimum amount of code, the mechanism used by `isend-mode` boils down to this:

```lisp
(with-current-buffer "*ipy*"
  (insert "foo")
  ;; For terminal buffers:
  (funcall (key-binding (kbd "RET")))
  ;; *OR*
  ;; for all other buffer types:
  ;;(term-send-input)
  )
```

**Comment by amelio-vazquez-reina** [comment] 2016-07-17 23:41
Thanks! What does:
```
(funcall (key-binding (kbd "RET")))
```
exactly do? 

Also, why is `term-send-input`the right command to use for *non*-terminal buffers? (based on your comment).

**Comment by amelio-vazquez-reina** [comment] 2016-07-17 23:42
By the way, I am noticing that the above already fails in the new IPython shell. 

When I run:
```
(with-current-buffer "ipy"
  (insert "foo = 10")
  (funcall (key-binding (kbd "RET")))
  )
```
I *momenarily* see foo=10 in the buffer (for less than a few ms), but I then just get a new *empty* line. It's as if it doesn't give time for the buffer to register the string or something.

**Comment by ffevotte** [comment] 2016-07-18 06:18
Sorry, I exchanged the logic when writing my answer above. `term-send-input` is the right command to use for terminal buffers. I edited my post above to reflect that.

For all other buffers, the fallback version is `(funcall (key-binding (kbd "RET")))`, which:

1. retrieves the command associated to <kbd>RET</kbd> in the current keymap
2. executes this command

**Comment by amelio-vazquez-reina** [comment] 2016-07-18 13:29
Thanks! This is really odd. I am able to do:
```
(with-current-buffer "ipy"
  (insert "%paste")
  (term-send-input)
  )
```
without problem. It always works (against the IPython 5 buffer). 

However, If I just do the usual `isend-send`, it almost never works the first few times, but then after a while (or after manually evaluating the code above), it starts to work.

**Comment by amelio-vazquez-reina** [comment] 2016-07-18 21:05
As a matter of fact, say I select associate a Python buffer to a `term` buffer that is running IPython called `ipy`, and then select and copy (save to the kill ring) some Python code. 

If I do:

```
 (with-current-buffer "ipy"
  (insert "%paste")
  (term-send-input)
  )
```
it **works.**

But this fails (it pastes some stuff, but in the wrong location ....)
```
(defun override-isend ()
  (interactive)
  (clipboard-kill-ring-save (point-min) (point-max))
  (with-current-buffer isend--command-buffer
  (insert "%paste")
  (term-send-input)
  )
)
```

**Comment by ffevotte** [comment] 2016-07-19 06:27
Just to be sure, do you mean that:

1. "%paste" is inserted in the terminal buffer
1. IPython reacts to it
1. the python code fragment from the kill ring is inserted in the terminal buffer...
1. ...but at the wrong location in the terminal buffer?

If that is the case, where exactly is the code fragment inserted? And also, is it executed by the python interpreter?


Thanks again for doing all this. I'm sorry I haven't had the time yet to install a recent enough IPython version to be able to test by myself.

**Comment by amelio-vazquez-reina** [comment] 2016-07-20 13:31
Thanks @ffevotte and no worries at all! You mentioned you didn't get notifications earlier, so just in case (no rush!), I left my updates here: https://github.com/ffevotte/isend-mode.el/issues/6. Thanks.

**Comment by ffevotte** [comment] 2016-07-20 13:37
Yes, I actually seem to receive direct notifications by e-mail if you @-mention me. Otherwise, I have to go to my dashboard to see your messages. There might be some setting available to fix this...

Anyway, I did receive your last comment on #6, I just did not happen to have time at home yesterday evening. If I get lucky, I'll have some time to look at the problem in more details this evening.

**Comment by ffevotte** [comment] 2016-07-20 20:03
I managed to reproduce the problem (thanks for your tip about anaconda, by the way). I think it has to do with IPython disliking cursor movement in the terminal buffer.

Could you please try replacing [line 272 of isend-mode.el](https://github.com/ffevotte/isend-mode.el/blob/master/isend-mode.el#L272) with one of the following options:

1. nothing
1. `(goto-char (process-mark (get-buffer-process (current-buffer))))`
1. `(term-send-down)`
1. `(let ((last-input-event ?>)) (term-send-raw-meta))`

Please tell me whether each one of these options avoids the problem.

If one (or some) of them work, you can use it as a workaround while I integrate it properly into `isend-mode`

**Comment by amelio-vazquez-reina** [comment] 2016-07-21 02:15
Thanks @ffevotte Just tried them all, one by one, fully closing emacs and restarting it each time and making sure `isend-mode.el` was updated, without luck. 

There was no visible difference between them.

**Comment by ffevotte** [comment] 2016-07-21 06:45
Damn, I thought at least solutions 2-4 would work!

I'll look again tonight...

**Comment by ffevotte** [comment] 2016-07-22 06:24
I tried reproducing your problem, but I could not: when I perform one of the changes mentioned above, everything works well.

Could you confirm that you tested with a minimal configuration file? And which emacs version do you use?

Also, could you confirm that something like that does not work for you? (Because it works perfectly in my setup)

```lisp
(defun override-isend ()
  (interactive)
  (with-current-buffer isend--command-buffer
    (insert "print 'OK'")
    (term-send-input)))
```

**Comment by amelio-vazquez-reina** [comment] 2016-07-23 18:07
Thanks @ffevotte your comment above made me wonder if there was a problem with the version of Emacs I have installed. I was using a snapshot from June. After upgrading to a more recent version (from yesterday), **everything** works again (the current `isend-mode` works!):

```
"GNU Emacs 25.0.95.1 (x86_64-apple-darwin15.5.0, NS appkit-1404.47 Version 10.11.5 (Build 15F34)) of 2016-07-23"
```

In case it helps for the future (although I don't think this interferes with the normal functioning of the package) I have:
```
(defadvice ansi-term (after advise-ansi-term-coding-system)
    (set-buffer-process-coding-system 'utf-8-unix 'utf-8-unix))
(ad-activate 'ansi-term)
```

Also:
```
(setq system-uses-terminfo nil)
```

**Comment by ffevotte** [comment] 2016-07-23 18:50
Nice, thanks for the update!

I'm closing the bug reports. Please feel free to reopen them if you still have problems.

**Closed by ffevotte** 2016-07-23 18:50 UTC
